# Generated by Django 5.2.6 on 2025-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
