# Generated by Django 5.2.6 on 2025-11-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard_page', '0002_registration_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='absent_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=15),
        ),
    ]
