# Generated by Django 5.2.6 on 2025-10-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='organization_name',
            field=models.CharField(db_column='organization_name', default='TEMP_MIGRATION_PLACEHOLDER', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
