# Generated by Django 5.2.6 on 2025-11-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0002_adminprofile_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
