# Generated by Django 5.2.6 on 2025-11-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0003_adminprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='token_created_at',
            new_name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
