# Generated by Django 5.2.6 on 2025-12-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0006_accesscoderequest_organizationaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscoderequest',
            name='cit_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
