# Generated by Django 5.2.6 on 2025-11-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manual_close_time',
            field=models.TimeField(blank=True, help_text='Optional cutoff time for registration if manual mode is set.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='manual_status_override',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('AVAILABLE', 'Available'), ('FULL', 'Full'), ('CLOSED', 'Closed'), ('ONGOING', 'Ongoing')], default='AUTO', max_length=50),
        ),
    ]
