# Generated by Django 5.2.6 on 2025-11-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard_page', '0002_event_manual_close_time_event_manual_status_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='manual_close_date',
            field=models.DateField(blank=True, help_text='The date when the manual override status will expire.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='manual_close_time',
            field=models.TimeField(blank=True, help_text='The time when the manual override status will expire.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='manual_status_override',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('OPEN_MANUAL', 'Registration Open (Manual Override)'), ('CLOSED_MANUAL', 'Registration Closed (Manual Override)'), ('ONGOING', 'Closed – Event Ongoing')], default='AUTO', max_length=50),
        ),
    ]
