# Generated by Django 5.2.6 on 2025-11-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard_page', '0003_event_manual_close_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='event_pictures/'),
        ),
    ]
