# Generated by Django 5.2.6 on 2025-11-21 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard_page', '0005_alter_event_id_alter_event_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.AddField(
            model_name='event',
            name='picture_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
